### ISSUE TITLE
doesnt work in version 6.6.2.0

### ISSUE THREAD

**Issue by on1l** [iMi-digital/shopware6-category-duplicator#10]
errors
: 
[{code: "0", status: "500", title: "Internal Server Error",…}]
0
: 
{code: "0", status: "500", title: "Internal Server Error",…}
code
: 
"0"
detail
: 
"in_array(): Argument #2 ($haystack) must be of type array, string given"
meta
: 
{trace: [,…],…}
status
: 
"500"
title
: 
"Internal Server Error"

**Comment by amenk** [comment]
Can you check the error log for the stack trace?

**Comment by on1l** [comment]
Hello @amenk 
![Screenshot_110](https://github.com/user-attachments/assets/d4ae6aa4-54f3-47ba-a39b-a944df4a6ea8)
![Screenshot_109](https://github.com/user-attachments/assets/2a8112d1-12b6-45cc-90e2-cdf00013e854)
![Screenshot_108](https://github.com/user-attachments/assets/58576f58-e443-48ff-b75c-feba9b6e8eeb)

**Comment by amenk** [comment]
Thank you for the details. We are currently not actively developing the plugin, but might come to the issue later.

Pull requests are very welcome though.

**Comment by kdambekalns** [comment]
My fault, I guess.
