### ISSUE TITLE
Error with Shopware 6.6.4.0: Make sure there is a loader supporting the "annotation" type.

### ISSUE THREAD

**Issue by kdambekalns** [iMi-digital/shopware6-category-duplicator#8]
After installation all I get in the admin UI is the same as when calling `cache:ckear`:

```
root@shopware:/var/www/acme.com# sudo -u www-data bin/console cache:clear

 // Clearing the cache for the prod environment with debug false

In Loader.php line 67:

  Cannot load resource "/var/www/acme.com/vendor/imi/shopware6-category-duplicator/src/Core/Framework/Api/Controller/CloneCategoryController.php".
  Make sure there is a loader supporting the "annotation" type.
```

**Comment by amenk** [comment]
Thanks for the report. 

I am checking internally if we saw this problem already.

Otherwise, would you be able to make a pull request?

**Comment by kdambekalns** [comment]
I can do PRs, but in this case I wouldn't even know wherev to begin, without some proper research… 😬

I mean, is this essentially a complaint about the `@Route` annotation? Why would that not be supported out of the box (anymore) in Shopware?

**Comment by amenk** [comment]
I found this:

https://forum.shopware.com/t/make-sure-there-is-a-loader-supporting-the-annotation-type/103580

**Comment by kdambekalns** [comment]
Fair enough!

Tested it locally, worked. I did not check if this still works in versions < 6.6, you might want to adjust the minimum dependency in the composer manifest…
